---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install: gem install bundler -v 1.17.2

script:
  - rake test

after_script:
  # coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
